import { answeredString, type FactKey } from "@lex/domain";
import { getCurrentRevision, getMatter, listMatterAnalyses, listMatterDocuments, listMatterDrafts } from "@lex/db";
import { ApiError, handle, requireUser } from "@/lib/api";
import { resolveCompanyForActor } from "@/lib/authz";
import { asActor } from "@/lib/db";

type Context={params:Promise<{companyId:string;matterId:string}>};
const h=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]!);
export const GET=handle(async (_request:Request,{params}:Context)=>{
  const user=await requireUser();const {companyId,matterId}=await params;const {company}=await resolveCompanyForActor(companyId,user.id);
  const data=await asActor(user.id,async db=>{const matter=await getMatter(db,companyId,matterId);if(!matter)throw new ApiError(404,"not_found","Matter not found");const revision=await getCurrentRevision(db,companyId);const documents=await listMatterDocuments(db,companyId,matterId);const analyses=await listMatterAnalyses(db,companyId,matterId);const drafts=await listMatterDrafts(db,companyId,matterId);return{matter,revision,documents,analyses,drafts};});
  const facts=data.revision?.facts??{};
  const keys:FactKey[]=["formation_country","formation_subdivision","industry","activities","registration_status","worker_locations","customer_data"];
  const factsHtml=keys.map(key=>{const v=answeredString(facts,key);return v?`<li>${h(key.replaceAll("_"," "))}: ${h(v)}</li>`:"";}).join("");
  const analysis=data.analyses[0];const draft=data.drafts[0];
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${h(data.matter.title)} — lawyer packet</title><style>body{font:15px/1.5 system-ui,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#172235}h1{font-size:30px}h2{margin-top:30px;border-bottom:1px solid #ccd3dc;padding-bottom:6px}article{border:1px solid #dce2e8;padding:14px;margin:10px 0;border-radius:8px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.5 inherit}.notice{padding:12px;background:#fff5de;border-left:4px solid #c4831e}@media print{body{margin:0;max-width:none}article{break-inside:avoid}}</style></head><body><p>CLEX · REVIEW PACKET</p><h1>${h(data.matter.title)}</h1><p class="notice">Unreviewed preparation material. No professional approval or legal compliance determination is implied.</p><p><strong>Company:</strong> ${h(company.name)}<br><strong>Matter:</strong> ${h(data.matter.kind)}<br><strong>Generated:</strong> ${h(new Date().toISOString())}<br><strong>Profile revision:</strong> ${h(data.revision?.version??"none")}</p><h2>Purpose and context</h2><p>${h(data.matter.summary||"No summary provided")}</p><ul>${Object.entries(data.matter.context).map(([k,v])=>`<li>${h(k.replaceAll("_"," "))}: ${h(v)}</li>`).join("")}</ul><h2>Confirmed company facts</h2><ul>${factsHtml||"<li>No confirmed profile facts</li>"}</ul><h2>Documents</h2><ul>${data.documents.map(d=>`<li>${h(d.filename)} — ${h(d.extractionStatus)}, SHA-256 ${h(d.sha256)}</li>`).join("")||"<li>No documents</li>"}</ul><h2>Latest analysis</h2>${analysis?`<p>${h(analysis.mode)} · ${h(analysis.status)} · ${h(analysis.createdAt)} · profile revision ID ${h(analysis.profileRevisionId||"none")}</p>${analysis.findings.map(f=>`<article><strong>${h(f.title)}</strong><p>${h(f.explanation)}</p><small>Company reason: ${h(f.companyReason)}</small>${f.documentExcerpt?`<blockquote>${h(f.documentExcerpt)}</blockquote>`:""}</article>`).join("")}<h3>Questions</h3><ol>${analysis.questions.map(q=>`<li>${h(q)}</li>`).join("")}</ol>`:"<p>No analysis yet</p>"}<h2>Latest working draft</h2>${draft?`<p>Version ${h(draft.version)} · ${h(draft.status)}</p><pre>${h(draft.body)}</pre>`:"<p>No draft yet</p>"}<h2>For the adviser</h2><p>Verify jurisdiction, assumptions, source currency, document completeness and legal effect. Mark corrections and unresolved points.</p></body></html>`;
  return new Response(html,{headers:{"Content-Type":"text/html; charset=utf-8","Content-Disposition":`inline; filename="matter-${matterId}.html"`,"Cache-Control":"private, no-store","Content-Security-Policy":"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'","X-Content-Type-Options":"nosniff"}});
});
