"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { MatterAction, MatterDocument, MatterDraft } from "@lex/db";

export function MatterWorkbench({companyId,matterId,documents,drafts,actions,modelReady,canEdit}:{companyId:string;matterId:string;documents:MatterDocument[];drafts:MatterDraft[];actions:MatterAction[];modelReady:boolean;canEdit:boolean}){
  const router=useRouter();const base=`/api/v1/companies/${companyId}/matters/${matterId}`;
  const [busy,setBusy]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [documentId,setDocumentId]=useState(documents.find(d=>d.extractionStatus==="readable")?.id||"");const [consent,setConsent]=useState(false);const [draftText,setDraftText]=useState(drafts[0]?.body||"");const [actionText,setActionText]=useState("");
  async function jsonRequest(url:string,method:string,body:unknown){const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Request failed");return data;}
  async function run(label:string,fn:()=>Promise<void>){setBusy(label);setError("");setNotice("");try{await fn();router.refresh();}catch(e){setError(e instanceof Error?e.message:"Request failed");}finally{setBusy("");}}
  async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const target=event.currentTarget;const form=new FormData(target);await run("upload",async()=>{const response=await fetch(`${base}/documents`,{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Upload failed");setDocumentId(data.document.id);target.reset();setNotice("File saved. Review its extraction status below.");});}
  return <div className="space-y-6">
    {error&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
    <section className="card p-6" id="documents"><div className="flex items-center justify-between gap-3"><div><span className="eyebrow">01 / Source material</span><h2 className="mt-1 text-xl font-semibold">Documents</h2></div><span className="text-sm text-slate-500">{documents.length} saved</span></div><p className="mt-2 text-sm text-slate-600">Upload the agreement you received, your existing draft, or meeting notes. TXT, DOCX and text PDFs up to 10 MB.</p>
      {canEdit&&<form onSubmit={upload} className="mt-4 flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-sm font-medium">Choose a document<input className="field mt-1" type="file" name="file" accept=".txt,.docx,.pdf,text/plain,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required/></label><button disabled={!!busy} className="button-secondary">{busy==="upload"?"Uploading…":"Upload"}</button></form>}
      <ul className="mt-4 divide-y divide-slate-100">{documents.map(d=><li key={d.id} className="flex flex-wrap items-center justify-between gap-2 py-3 text-sm"><div><a className="font-medium underline" href={`${base}/documents/${d.id}`}>{d.filename}</a><p className="text-xs text-slate-500">{Math.ceil(d.byteSize/1024)} KB · {d.extractionStatus==="readable"?"Text extracted":"Text unreadable; OCR or a text copy needed"}</p></div>{canEdit&&<button className="text-red-700 underline" disabled={!!busy} onClick={()=>{if(window.confirm("Delete this file and its derived analyses and drafts?"))void run("delete",async()=>{const response=await fetch(`${base}/documents/${d.id}`,{method:"DELETE"});if(!response.ok)throw new Error("Could not delete document");setNotice("Document and its derived results removed.");});}}>Delete</button>}</li>)}{!documents.length&&<li className="py-3 text-sm text-slate-500">No document uploaded yet. You can still prepare questions from the matter details.</li>}</ul>
    </section>
    <section className="card p-6" id="analysis"><span className="eyebrow">02 / Company-specific review</span><h2 className="mt-1 text-xl font-semibold">Analyse this matter</h2><p className="mt-2 text-sm text-slate-600">The analysis uses your confirmed company profile and matter details. Findings are unreviewed suggestions; they do not establish legal compliance.</p>
      <div className="mt-4 flex flex-wrap items-end gap-3"><label className="min-w-48 flex-1 text-sm font-medium">Document to analyse<select className="field mt-1" value={documentId} onChange={e=>setDocumentId(e.target.value)}><option value="">Matter details only</option>{documents.map(d=><option key={d.id} value={d.id}>{d.filename}{d.extractionStatus!=="readable"?" (unreadable)":""}</option>)}</select></label>{canEdit&&<button disabled={!!busy||(modelReady&&!consent)} className="button-primary" onClick={()=>void run("analysis",async()=>{await jsonRequest(`${base}/analyses`,"POST",{documentId:documentId||null,allowExternalProcessing:consent});setNotice("Analysis saved below.");})}>{busy==="analysis"?"Analysing…":modelReady?"Run live analysis":"Prepare review questions"}</button>}</div>
      {modelReady?<label className="mt-3 flex gap-2 text-xs text-slate-600"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to send the selected document text and company context to the configured AI provider for this analysis.</span></label>:<p className="mt-3 text-xs text-amber-800">This runs a local preparation checklist and is labelled as such.</p>}
    </section>
    <section className="card p-6" id="drafts"><span className="eyebrow">03 / Working document</span><h2 className="mt-1 text-xl font-semibold">Draft workspace</h2><p className="mt-2 text-sm text-slate-600">Create a basic outline from known terms, then edit and save a new version. It is a preparation draft, not a reviewed agreement.</p><textarea className="field mt-4 font-mono text-sm" rows={16} value={draftText} onChange={e=>setDraftText(e.target.value)} placeholder="Choose Create outline, or write your own draft here." disabled={!canEdit}/>{canEdit&&<div className="mt-3 flex flex-wrap gap-2"><button disabled={!!busy} className="button-secondary" onClick={()=>void run("outline",async()=>{const data=await jsonRequest(`${base}/drafts`,"POST",{});setDraftText(data.draft.body);setNotice("Outline saved as version "+data.draft.version+".");})}>Create outline</button><button disabled={!!busy||!draftText.trim()} className="button-primary" onClick={()=>void run("draft",async()=>{const data=await jsonRequest(`${base}/drafts`,"POST",{body:draftText});setNotice("Draft saved as version "+data.draft.version+".");})}>{busy==="draft"?"Saving…":"Save new version"}</button></div>}<p className="mt-3 text-xs text-slate-500">{drafts.length?`${drafts.length} saved version(s); latest v${drafts[0]?.version}. Export the review packet to share with your lawyer.`:"No saved draft yet."}</p></section>
    <section className="card p-6" id="actions"><span className="eyebrow">04 / Follow-through</span><h2 className="mt-1 text-xl font-semibold">Action items</h2>{canEdit&&<form className="mt-4 flex gap-2" onSubmit={e=>{e.preventDefault();void run("action",async()=>{await jsonRequest(`${base}/actions`,"POST",{text:actionText});setActionText("");});}}><input className="field" value={actionText} onChange={e=>setActionText(e.target.value)} placeholder="e.g. Confirm worker location with counsel" required maxLength={1000}/><button className="button-secondary" disabled={!!busy}>Add</button></form>}<ul className="mt-3 divide-y divide-slate-100">{actions.map(a=><li key={a.id} className="flex items-start gap-3 py-3 text-sm"><input type="checkbox" aria-label={`Complete ${a.text}`} checked={a.status==="done"} disabled={!canEdit||!!busy} onChange={e=>void run("action",async()=>{await jsonRequest(`${base}/actions/${a.id}`,"PATCH",{status:e.target.checked?"done":"open"});})}/><span className={a.status==="done"?"text-slate-400 line-through":""}>{a.text}</span></li>)}{!actions.length&&<li className="py-3 text-sm text-slate-500">No actions recorded yet.</li>}</ul></section>
  </div>;
}
